version: '3'
services:
  spring-boot-app:
    image: spring-boot:latest
    container_name: spring-boot-app
    build:
      context: ./spring-boot
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/appcibertec2024
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
    depends_on:
      - mysql-db

  angular-app:
    image: app-cibertec:latest
    container_name: angular-app
    build:
      context: ./app-cibertec
    ports:
      - "4200:80"

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: appcibertec2024
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/:/docker-entrypoint-initdb.d/

volumes:
  db_data:
